var conkitty = require('../');
var should = require('should');
var path = require('path');
var File = require('gulp-util').File;
var Buffer = require('buffer').Buffer;
var fs = require('fs');
require('mocha');

describe('gulp-conkitty', function() {
    describe('conkitty()', function() {
        testConkitty(
            {
                common: 'tmp/ok.common',
                templates: 'tmp/ok',
                sourcemap: 'tmp/ok.map',
                deps: true
            },
            [
                'test/tpl1.ctpl',
                'test/tpl2.ctpl'
            ],
            [
                'tmp/ok.common', '/*!\n * concat.js v0.9.',
                'tmp/ok', '// This file is autogenerated.',
                'tmp/ok.map', '{"version":3',
                'test/file3.css', '.clsss3 {}',
                'test/file2.js', 'function func2() {}',
                'test/file1.css', '.class1 {}',
                'test/file2.css', '.class2 {}',
                'test/file1.js', 'function func1() {}'
            ]
        );

        testConkitty(
            {
                common: 'tmp/empty.common',
                templates: 'tmp/empty'
            },
            ['test/tpl3.ctpl'],
            []
        );

        testConkitty(
            {
                templates: 'tmp/nocommon',
                deps: true
            },
            ['test/tpl2.ctpl'],
            [
                'tmp/nocommon', '// This file is autogenerated.',
                'test/file3.css', '.clsss3 {}',
                'test/file2.js', 'function func2() {}'
            ]
        );

        testConkitty(
            {
                templates: 'tmp/notcwd',
                deps: {
                    '..': 'tmp/rebase1/',
                    '../..': 'tmp/rebase2',
                    '../../file1.js': 'tmp/rebase3/file1.js'
                }
            },
            [
                '../../tpl1.ctpl',
                '../../tpl2.ctpl',
                '../tpl4.ctpl',
                'tpl5.ctpl'
            ],
            [
                'tmp/notcwd', '// This file is autogenerated.',

                'tmp/rebase2/file3.css', '.clsss3 {}',
                'tmp/rebase2/file2.js', 'function func2() {}',
                'tmp/rebase2/file1.css', '.class1 {}',
                'tmp/rebase2/file2.css', '.class2 {}',

                'tmp/rebase3/file1.js', 'function func1() {}',

                'tmp/rebase1/file4.css', '.class4 {}',
                'tmp/rebase1/file4.js', '// file4.js',

                'file5.css', '.class5 {}'
            ],
            true // Not cwd test.
        );

        function testConkitty(settings, files, results, notcwd) {
            it('should compile templates', function(done) {
                if (notcwd) {
                    var oldcwd = process.cwd();
                    process.chdir(path.join(oldcwd, 'test', 'sub', 'subsub'));
                }

                var stream = conkitty(settings);

                stream.on('data', function (file) {
                    var expectedFilename = results.shift(),
                        expectedHead = results.shift();

                    should.exist(file);
                    should.exist(file.relative);
                    should.exist(file.contents);
                    should.exist(expectedFilename);
                    should.exist(expectedHead);

                    var retFilename = path.resolve(file.path);
                    retFilename.should.equal(path.resolve(expectedFilename));
                    file.relative.should.equal(expectedFilename);

                    Buffer.isBuffer(file.contents).should.equal(true);
                    file.contents.toString().substring(0, expectedHead.length).should.equal(expectedHead);

                    if (results && !results.length) {
                        results = null;
                        if (notcwd) {
                            process.chdir(path.join(oldcwd));
                        }
                        done();
                    }
                });

                files.forEach(function (filename) {
                    filename = path.resolve(filename);
                    stream.write(new File({
                        path: filename,
                        contents: fs.readFileSync(filename)
                    }));
                });

                stream.end();

                if (results && !results.length) {
                    results = null;
                    if (notcwd) {
                        process.chdir(path.join(oldcwd));
                    }
                    done();
                }
            });
        }
    });
});
